In [1]:
import numpy as np

- create
- basic operation
- math operation
- indexing and slicing
- boolean  filter

In [3]:
x= np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [5]:
a= np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [8]:
z=[0,1,2,3,4,5,6,7,8,9]
nz= np.array([z,z,z,z,z,z,z,z,z,z])
print(nz)
print(nz.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(10, 10)


In [11]:
z=[0,1,2,3,4,5,6,7,8,9]
nz= np.array([z]*10)
print(nz)
print(nz.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(10, 10)


- random
- arange
- linspace

In [12]:
np.random.rand(3,3)

array([[0.47715198, 0.13013952, 0.64309293],
       [0.0172022 , 0.01108371, 0.36275539],
       [0.18244985, 0.05709687, 0.10040798]])

In [15]:
r1=np.random.randint(-5,6,(5,5))
print(r1)

[[-2  3  3 -5 -3]
 [-1  4 -2  5  5]
 [-1  1 -5  5 -2]
 [-4 -4 -5  5 -2]
 [ 0 -1 -3  0 -5]]


In [21]:
#start,stop, gap
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [24]:
#start, stop, number of items
np.linspace(0,50, 10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

Array attributes
- shape
- dtype
- ndim
- size

basic operation
- sum
- mean
- max
- min
- std 
- reshape
- transpose
- flatten

In [26]:
x.dtype

dtype('int64')

In [27]:
x= np.random.rand(3,3)
x.dtype

dtype('float64')

In [28]:
x.ndim #no of deminsions

2

In [32]:
z=np.random.randint(1,5,(3,3,3))
z.ndim
#print(z)

3

In [33]:
z.sum()

np.int64(64)

In [43]:
a= np.random.rand(2,3)
print(a.sum())
print(a.sum(axis=0)) # colume wise sum
print(a.sum(axis=1))# row wise sum


print(a.mean())
print(a.min())
print(a.max())
print(a.std())
print(a.var())
# all  the methods can be used with axis 


3.7981505787292305
[0.96768128 1.11715372 1.71331558]
[2.52132976 1.27682082]
0.6330250964548717
0.12444868539483611
0.9927050371370633
0.3484549573692901
0.12142085731523378


In [45]:
z=np.random.randint(11,99,(5,5))
print(z)
print("transpose")
print(z.transpose()) #(z,T)
print('flatten')
print(z.flatten())

[[92 73 23 29 57]
 [38 21 92 12 21]
 [25 27 68 13 39]
 [72 28 64 88 86]
 [16 65 45 71 85]]
transpose
[[92 38 25 72 16]
 [73 21 27 28 65]
 [23 92 68 64 45]
 [29 12 13 88 71]
 [57 21 39 86 85]]
flatten
[92 73 23 29 57 38 21 92 12 21 25 27 68 13 39 72 28 64 88 86 16 65 45 71
 85]


In [47]:
a=np.random.randint(1,10,(4,5))
print(a)
print(a.reshape(20))
print(a.reshape(5,4))
print(a.reshape(2,10))
print(a.reshape(10,2))
#print(a.reshape(5,2,2))

[[5 8 7 4 5]
 [9 4 2 1 3]
 [4 6 8 7 2]
 [1 3 5 9 6]]
[5 8 7 4 5 9 4 2 1 3 4 6 8 7 2 1 3 5 9 6]
[[5 8 7 4]
 [5 9 4 2]
 [1 3 4 6]
 [8 7 2 1]
 [3 5 9 6]]
[[5 8 7 4 5 9 4 2 1 3]
 [4 6 8 7 2 1 3 5 9 6]]
[[5 8]
 [7 4]
 [5 9]
 [4 2]
 [1 3]
 [4 6]
 [8 7]
 [2 1]
 [3 5]
 [9 6]]


In [49]:
m1=np.array([[1,2],[8,9]])
m2=np.array([[3,4],[6,7]])
print(m1)
print(m2)

[[1 2]
 [8 9]]
[[3 4]
 [6 7]]


In [ ]:
print(m1 + m2)
print(m1 - m2)
print(m1 / m2)# element wise division
print(m1 * m2)# element wise multiplation
print(m1 @ m2)# matrix multiplation
print(m1.dot(m2))# matrix multiplation

In [50]:
# when using  matrix and scalar
print(a-10) #broadcasting
print(a*10) #broadcasting
print(a/10) 
print(a+10)

[[-5 -2 -3 -6 -5]
 [-1 -6 -8 -9 -7]
 [-6 -4 -2 -3 -8]
 [-9 -7 -5 -1 -4]]
[[50 80 70 40 50]
 [90 40 20 10 30]
 [40 60 80 70 20]
 [10 30 50 90 60]]
[[0.5 0.8 0.7 0.4 0.5]
 [0.9 0.4 0.2 0.1 0.3]
 [0.4 0.6 0.8 0.7 0.2]
 [0.1 0.3 0.5 0.9 0.6]]
[[15 18 17 14 15]
 [19 14 12 11 13]
 [14 16 18 17 12]
 [11 13 15 19 16]]


In [53]:
#indexing
a[0]
a[0,0]
a[0][0]

np.int32(5)

In [54]:
#slicing
x=np.random.randint(1,10,(5,5))
print(x)

[[9 1 9 9 6]
 [1 9 3 3 4]
 [9 2 1 4 8]
 [7 5 7 5 3]
 [3 4 1 3 8]]


In [61]:
print(x[:,0]) #first
print(x[:,1]) #last
print(x[:,:3]) # first 3 colume

array([[9, 1, 9],
       [1, 9, 3],
       [9, 2, 1],
       [7, 5, 7],
       [3, 4, 1]], dtype=int32)

In [60]:
x[1:4,1:4]
x[1:-1,1:-1]

array([[9, 3, 3],
       [2, 1, 4],
       [5, 7, 5]], dtype=int32)